name: "Changelog Adder"
description: "Add changelog entries to PRs using Claude Code"

inputs:
  anthropic_oauth_token:
    description: "Claude Code OAuth token"
    required: true
  github_token:
    description: "GitHub token for PR operations"
    required: false
    default: ${{ github.token }}

outputs:
  entry_created:
    description: "Whether a changelog entry was created"
    value: ${{ steps.detect.outputs.created }}
  entry_files:
    description: "Newline-separated paths to changelog entries"
    value: ${{ steps.check.outputs.files || steps.detect.outputs.files }}
  skipped:
    description: "Whether the action was skipped (entries already exist)"
    value: ${{ steps.check.outputs.skipped }}

runs:
  using: "composite"
  steps:
    # Step 1: Check if entries for this PR already exist
    - name: Check for existing entries
      id: check
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        entry_files=$(find . -path "*/changelog/unreleased/*.md" -exec grep -l "^pr: $PR_NUMBER$" {} \; 2>/dev/null || true)
        if [ -n "$entry_files" ]; then
          echo "Changelog entries for PR #$PR_NUMBER already exist:"
          echo "$entry_files"
          echo "skipped=true" >> $GITHUB_OUTPUT
          {
            echo "files<<EOF"
            echo "$entry_files"
            echo "EOF"
          } >> $GITHUB_OUTPUT
        else
          echo "skipped=false" >> $GITHUB_OUTPUT
        fi

    # Step 2: Capture existing changelog files
    - name: Capture existing changelog files
      if: steps.check.outputs.skipped != 'true'
      id: before
      shell: bash
      run: |
        find . -path "*/changelog/unreleased/*.md" -type f 2>/dev/null | sort > /tmp/changelog-before.txt

    # Step 3: Run Claude with changelog:adder agent
    - name: Run Claude changelog:adder
      if: steps.check.outputs.skipped != 'true'
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.anthropic_oauth_token }}
        github_token: ${{ inputs.github_token }}
        prompt: |
          REPO: ${{ github.repository }}
          PR NUMBER: ${{ github.event.pull_request.number }}
          AUTHOR: ${{ github.event.pull_request.user.login }}

          Analyze this PR and run /changelog:add if there are user-facing changes.
          If you create an entry, commit it to this PR branch.
          If there are no user-facing changes, do nothing.
        claude_args: "--agent changelog:adder --allowedTools Read,Glob,Grep,Bash,Write,Edit,Skill"
        plugin_marketplaces: "https://github.com/tenzir/claude-plugins.git"
        plugins: |
          changelog@tenzir
          git@tenzir
          prose@tenzir

    # Step 4: Detect new changelog entries
    - name: Detect new entries
      if: steps.check.outputs.skipped != 'true'
      id: detect
      shell: bash
      run: |
        find . -path "*/changelog/unreleased/*.md" -type f 2>/dev/null | sort > /tmp/changelog-after.txt
        new_files=$(comm -13 /tmp/changelog-before.txt /tmp/changelog-after.txt)

        if [ -z "$new_files" ]; then
          echo "created=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "created=true" >> $GITHUB_OUTPUT
        {
          echo "files<<EOF"
          echo "$new_files"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    # Step 5: Post PR comment
    - name: Post PR comment
      if: steps.check.outputs.skipped == 'true' || steps.detect.outputs.created == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
        ENTRY_FILES: ${{ steps.check.outputs.files || steps.detect.outputs.files }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        MODE: ${{ steps.check.outputs.skipped == 'true' && 'existing' || 'created' }}
      run: ${{ github.action_path }}/scripts/post-comment.sh
